### ISSUE TITLE
Change import tool plot from diamond to smaller circle

### ISSUE THREAD

**Issue by shifucun** [datacommonsorg/import#169]
For long time series, the plot get dense the diamonds can overlap with each other.

![image](https://user-images.githubusercontent.com/5951856/179273105-7c3a458d-0118-4f3e-b70e-b29ce79e896b.png)

**Comment by enjoythecode** [comment]
Hi @shifucun, thanks for the request. Are you able to provide a dataset to reproduce this?

In terms of solutions, I have some ideas (and likely more things we can do), roughly ordered in complexity + completeness;
1. Simply decrease the diamond size and/or make into a circle
2. Add a flag to customize the size of the diamond/circle
3. Move to JavaScript based plotting that is easier to customize either automatically based on the number of points, or manually using a button

**Comment by enjoythecode** [comment]
I will create 2 draft PRs, one for making the diamond smaller, one for replacing it with a small circle.

To reproduce those changes on your dataset, you can run clone those branches, `mvn package`, and then run the tool as you are used to.

**Comment by enjoythecode** [comment]
See draft PRs;

1. Small diamond: https://github.com/datacommonsorg/import/pull/171
2. Small circle: https://github.com/datacommonsorg/import/pull/170

Note that these are too small for datasets with few datapoints; so the final implementation should have a command line argument to specify the size. We can use these to see which size better supports large timeseries, and then I can write a PR with the flags.

**Comment by shifucun** [comment]
I like the small circle option. Looking at the test html file, seems the dot and line are disconnected. After fixing that, I would vote for the small circle change.

![image](https://user-images.githubusercontent.com/5951856/179284064-9cb9754e-5bec-422f-81b1-ceae3ad43f3e.png)

**Comment by enjoythecode** [comment]
Closed by #170
