### ISSUE TITLE
Add support for countryAlpha3Code and countryNumericCode

### ISSUE THREAD

**Issue by pulkit-s** [datacommonsorg/import#181]
countryAlpha3Code and countryNumericCode throw resolution errors when used with the import tool

**Comment by pulkit-s** [comment]
Sample error:
{
    "level": "LEVEL_ERROR",
    "location": {
      "file": "processed_data.csv",
      "lineNumber": "2"
    },
    "userMessage": "Failed to assign DCID :: type: 'Country', node: 'processed_data/E0/ee34cab1-5819-179f-a182-1b856594e76c'",
    "counterKey": "Resolution_DcidAssignmentFailure_Country"
  }

tmcf:
Node: E:processed_data->E0
typeOf: dcs:Country
countryAlpha3Code: C:processed_data->country

Node: E:processed_data->E1
typeOf: dcs:StatVarObservation
value: C:processed_data->Tonnes Co2e
unit: dcid:MetricTonCO2e
observationAbout: E:processed_data->E0
variableMeasured: C:processed_data->statvar
observationDate: C:processed_data->year

countryAlpha3Code is not resolvable: https://github.com/datacommonsorg/import/blob/master/util/src/main/java/org/datacommons/util/Vocabulary.java#L269

countryNumericCode is not resolvable either:
https://github.com/datacommonsorg/website/blob/master/static/js/import_wizard/utils/detect_place.ts#L47-L51

**Comment by pulkit-s** [comment]
work done in cl/464955055 , https://github.com/datacommonsorg/mixer/pull/879 and https://github.com/datacommonsorg/import/pull/183 fixes this

**Comment by pradh** [comment]
Those changes go in:
1. import servers / pipelines (autopushed)
2. recon service (manual)
3. dc-import tool rebuild/release (manual)

We probably want to handle (2).

**Comment by pulkit-s** [comment]
Is there a readme/doc I could follow to manually release the service?

**Comment by pradh** [comment]
@shifucun helped with it last time.  Bo, I forget where the doc was.

The import-tool uses the staging instance - https://github.com/datacommonsorg/import/blob/master/util/src/main/java/org/datacommons/util/ExternalIdResolver.java#L35

**Comment by shifucun** [comment]
I can help release to staging. We are planning to move service into mixer, so this won't need a separate release. @Fructokinase

**Comment by shifucun** [comment]
Released to recon-staging. Please verify.
