### ISSUE TITLE
Additional error checks in dc-import lint

### ISSUE THREAD

**Issue by ajaits** [datacommonsorg/import#189]
Flag the following errors in dc-import:

1. missing 'name' in schema node [name.isEmpty() check](https://www.google.com/url?sa=D&q=https%3A%2F%2Fgithub.com%2Fdatacommonsorg%2Fimport%2Fblob%2Fb149cb93001beea52a015a3c895c5802cc35af17%2Futil%2Fsrc%2Fmain%2Fjava%2Forg%2Fdatacommons%2Futil%2FMcfChecker.java%23L659)

2. invalid value for observationPeriod which is expected to have values in ISO 8610 format : "P<N>[DWMY]" or "PT<N>[HMS]"

**Comment by hareesh-ms** [comment]
Tracked in internal bug
