### ISSUE TITLE
Warn on duplicate nodes in the MCF

### ISSUE THREAD

**Issue by ajaits** [datacommonsorg/import#67]
Generate a warning when there are duplicate nodes in the MCFs with the same set of properties.

Nodes with the same dcid, but differences in PVs could be reported as errors.

**Comment by pradh** [comment]
There are legitimate cases where a node's DCID might have PVs coming from different files (e.g., geos), or could be repeated for nodes generated from CSV (e.g., [tmcf](https://github.com/datacommonsorg/data/blob/master/scripts/covid19_india/medical_tests_in_data/COVID19_tests_india.tmcf), [csv](https://github.com/datacommonsorg/data/blob/master/scripts/covid19_india/medical_tests_in_data/test_data/test2_expected_data.csv)).

And we have a "merging" functionality that deduplicates PVs of the same DCID.

Is this bug specifically about StatVars?  For that I think we could have a targeted check like this:
1. When StatVar nodes have the same content (aka generatd DCID), cannot have diverging assigned DCID
2. A StatVar DCID cannot be assigned to StatVar nodes with different content.

Would that work?

**Comment by ajaits** [comment]
On Thu, 16 Sept 2021 at 07:32, Prashanth R ***@***.***> wrote:

> There are legitimate cases where a node's DCID might have PVs coming from
> different files (e.g., geos), or could be repeated for nodes generated from
> CSV (e.g., tmcf
> <https://github.com/datacommonsorg/data/blob/master/scripts/covid19_india/medical_tests_in_data/COVID19_tests_india.tmcf>,
> csv
> <https://github.com/datacommonsorg/data/blob/master/scripts/covid19_india/medical_tests_in_data/test_data/test2_expected_data.csv>
> ).
>
> And we have a "merging" functionality that deduplicates PVs of the same
> DCID.
>
> Is this bug specifically about StatVars?
>
Yes, this was in reference to a statvar mcf for a single import. Normally
we don't expect an import to generate duplicate StatVars. In this case some
statvars became dups as they were missing other distinguishing properties.
This is likely specific to imports. We could add a utility class that the
import scripts could use to emit statvar mcf with optional checks for dups.


> For that I think we could have a targeted check like this:
>
>    1. When StatVar nodes have the same content (aka generatd DCID),
>    cannot have diverging assigned DCID
>    2. A StatVar DCID cannot be assigned to StatVar nodes with different
>    content.
>
> Yes, both these checks would be useful.

I think part of this is covered in dc-import lint as I got an error when
the properties for the statvar were the same but had different dcids in
prod (from a different import) and the local mcf file. Is the API able to
lookup a statvar based on the properties?

**Comment by pradh** [comment]
> We could add a utility class that the import scripts could use to emit statvar mcf with optional checks for dups.

The check (2) above should catch this, right?

> I think part of this is covered in dc-import lint as I got an error when the properties for the statvar were the same but had different dcids in prod (from a different import) and the local mcf file. Is the API able to lookup a statvar based on the properties?

We would check that a SV reference (from SVObs) resolves either locally or in KG, but I don't think we compare its content. Do you remember the counter you refer to?

**Comment by ajaits** [comment]
On Thu, 16 Sept 2021 at 20:26, Prashanth R ***@***.***> wrote:

> We could add a utility class that the import scripts could use to emit
> statvar mcf with optional checks for dups.
>
> The check (2) above should catch this, right?
>
> I think part of this is covered in dc-import lint as I got an error when
> the properties for the statvar were the same but had different dcids in
> prod (from a different import) and the local mcf file. Is the API able to
> lookup a statvar based on the properties?
>
> We would check that a SV reference (from SVObs) resolves either locally or
> in KG, but I don't think we compare its content. Do you remember the
> counter you refer to?
>
Sorry I just remembered that this issue of different dcid for statvars with
the same set of properties was caught by the stat_vars_checker unittest.
Would be good to have these checks in dc-import as well.

**Comment by pradh** [comment]
The new checker for SVs was added in https://github.com/datacommonsorg/import/pull/71
